### ISSUE TITLE
pwn16 id 00196250 missing

### ISSUE THREAD

**Issue by drevicko** [globalwordnet/ili#1]
wn16 has these entries:

> data.adj:00196128 00 a 01 unalarming 0 003 & 00196250 a 0000 = 05590744 n 0000 ! 00192906 a 0101 | not alarming; assuaging alarm  
> data.adj:00196250 00 s 03 calming 0 lulling 0 quietening 0 001 & 00196128 a 0000 | causing to become tranquil  

Note that this is also missing in TALP. It's the only synset id in wordnet-affect that's not covered.

wn 3.0 has these related entries:

> data.adj:00196560 00 a 01 unalarming 0 002 = 07519773 n 0000 ! 00193015 a 0101 | not alarming; assuaging alarm  
> data.noun:01150938 04 n 02 appeasement 0 calming 0 003 @ 01123598 n 0000 ~ 01151097 n 0000 ~ 01151407 n 0000 | the act of appeasing (as by acceding to the demands of)  
> data.noun:01827202 05 n 01 halcyon 1 001 @ 09484664 n 0000 | a mythical bird said to breed at the time of the winter solstice in a nest floating on the sea and to have the power of calming the winds and waves  
> data.noun:03713736 06 n 09 major_tranquilizer 0 major_tranquillizer 0 major_tranquilliser 0 antipsychotic_drug 0 antipsychotic_agent 0 antipsychotic 0 neuroleptic_drug 0 neuroleptic_agent 0 neuroleptic 0 012 @ 04470232 n 0000 ~ 03023175 n 0000 ~ 03053272 n 0000 ~ 03203641 n 0000 ~ 03371258 n 0000 ~ 03480186 n 0000 ~ 03694490 n 0000 ~ 03780896 n 0000 ~ 04007239 n 0000 ~ 04425262 n 0000 ~ 04425656 n 0000 ~ 14941884 n 0000 | tranquilizer used to treat psychotic conditions when a calming effect is desired  
> data.noun:04260816 06 n 01 soothing_syrup 0 001 @ 03740161 n 0000 | medicine in the form of a syrup that has a calming effect  
>

**Comment by jmccrae** [comment]
Hi, these terms do not exist in WordNet 3.0, so there is no mapping.

This is also due to the TALP mappings not how they are converted here.
